default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: medlink_dev

test:
  <<: *default
  database: medlink_test

production:
  <<: *default
  database: medlink_prod
